





//--------------------------------------------------------------------

var sub_positions_full_list = ["F-1", "F-2", "F-3", "F-4","S-1", "S-2", "S-3", "S-4"];
var overhead_wires_full_list = ["","Yes", "No"];
var concrete_completeds_full_list = ["","Yes", "No"];
var post_inspecteds_full_list = ["","Yes", "No"];


//-------------------------------------------------------------------------
var species_full_list =[

{name:'ABYSSINIAN BANANA'                  , code:''},
{name:'ACACIA SPECIES'                     , code:''},
{name:'AFRICAN FERN PINE'                  , code:''},
{name:'AFRICAN SUMAC'                      , code:''},
{name:'AFRICAN TULIP TREE'                 , code:''},
{name:'ALEPPO PINE'                        , code:''},
{name:'ALLIGATOR JUNIPER'                  , code:''},
{name:'ALMOND'                             , code:''},
{name:'AMERICAN ARBORVITAE'                , code:''},
{name:'AMERICAN CHESTNUT'                  , code:''},
{name:'AMERICAN ELM'                       , code:''},
{name:'AMERICAN HOLLY'                     , code:''},
{name:'AMERICAN MOUNTAIN ASH'              , code:''},
{name:'AMERICAN SWEETGUM'                  , code:''},
{name:'AMERICAN SYCAMORE'                  , code:''},
{name:'AMERICAN WHITE ASH'                 , code:''},
{name:'APRICOT'                            , code:''},
{name:'ARAUCARIA SPECIES'                  , code:''},
{name:'ARIZONA ASH'                        , code:''},
{name:'ARIZONA CYPRESS'                    , code:''},
{name:'ARROYO WILLOW'                      , code:''},
{name:'ATHEL TREE'                         , code:''},
{name:'ATLAS CEDAR'                        , code:''},
{name:'AUSTRALIAN BRUSH CHERRY'            , code:''},
{name:'AUSTRALIAN FAN PALM'                , code:''},
{name:'AUSTRALIAN JUNIPER-MYRTLE'          , code:''},
{name:'AUSTRALIAN TEA TREE'                , code:''},
{name:'AUSTRALIAN TREE FERN'               , code:''},
{name:'AUSTRALIAN WILLOW'                  , code:''},
{name:'AUSTRIAN PINE'                      , code:''},
{name:'AVOCADO'                            , code:''},
{name:'BAILEY ACACIA'                      , code:''},
{name:'BALD CYPRESS'                       , code:''},
{name:'BALSAM POPLAR'                      , code:''},
{name:'BANYAN FIG'                         , code:''},
{name:'BECHTEL CRABAPPLE'                  , code:''},
{name:'BEECH'                              , code:''},
{name:'BEEFWOOD'                           , code:''},
{name:'BENGAL PALM'                        , code:''},
{name:'BIGLEAF MAPLE'                      , code:''},
{name:'BISHOP PINE'                        , code:''},
{name:'BLACK ACACIA'                       , code:''},
{name:'BLACK ALDER'                        , code:''},
{name:'BLACK COTTONWOOD'                   , code:''},
{name:'BLACK LOCUST'                       , code:''},
{name:'BLACK MULBERRY'                     , code:''},
{name:'BLACK WALNUT'                       , code:''},
{name:'BLACK WILLOW'                       , code:''},
{name:'BLUE ATLAS CEDAR'                   , code:''},
{name:'BLUE BLOSSOM'                       , code:''},
{name:'BLUE ELDERBERRY'                    , code:''},
{name:'BLUE GUM'                           , code:''},
{name:'BLUE POTATO BUSH'                   , code:''},
{name:'BO TREE'                            , code:''},
{name:'BOTTLE TREE'                        , code:''},
{name:'BOTTLEBRUSH'                        , code:''},
{name:'BOWER WATTLE'                       , code:''},
{name:'BOX ELDER'                          , code:''},
{name:'BRADFORD PEAR'                      , code:''},
{name:'BRAZILIAN PEPPER'                   , code:''},
{name:'BRAZILWOOD'                         , code:''},
{name:'BRISBANE BOX'                       , code:''},
{name:'BRONZE LOQUAT'                      , code:''},
{name:'BRUSH CHERRY'                       , code:''},
{name:'BUNYA-BUNYA TREE'                   , code:''},
{name:'BUSHY BLUE GUM'                     , code:''},
{name:'BUSHY YATE'                         , code:''},
{name:'BUSHY YATE/LEHMANS YATE'            , code:''},
{name:'CAJEPUT TREE'                       , code:''},
{name:'CALABRIAN PINE'                     , code:''},
{name:'CALIFORNIA BAY'                     , code:''},
{name:'CALIFORNIA BIG TREE'                , code:''},
{name:'CALIFORNIA BLACK OAK'               , code:''},
{name:'CALIFORNIA BLACK WALNUT'            , code:''},
{name:'CALIFORNIA BUCKEYE'                 , code:''},
{name:'CALIFORNIA ELDERBERRY'              , code:''},
{name:'CALIFORNIA FAN PALM'                , code:''},
{name:'CALIFORNIA JUNIPER'                 , code:''},
{name:'CALIFORNIA NUTMEG'                  , code:''},
{name:'CALIFORNIA PEPPER'                  , code:''},
{name:'CALIFORNIA PRIVET'                  , code:''},
{name:'CALIFORNIA SCRUB OAK'               , code:''},
{name:'CALIFORNIA SYCAMORE'                , code:''},
{name:'CAMPHOR TREE'                       , code:''},
{name:'CANARY ISLAND DATE PALM'            , code:''},
{name:'CANARY ISLAND PINE'                 , code:''},
{name:'CANOE BIRCH'                        , code:''},
{name:'CAPE CHESTNUT'                      , code:''},
{name:'CAPE PITTOSPORUM'                   , code:''},
{name:'CARIBBEE ROYSTONEA PALM'            , code:''},
{name:'CAROB'                              , code:''},
{name:'CAROLINA LAUREL CHERRY'             , code:''},
{name:'CAROLINA POPLAR'                    , code:''},
{name:'CARROTWOOD'                         , code:''},
{name:'CATALINA CHERRY'                    , code:''},
{name:'CATALINA IRONWOOD'                  , code:''},
{name:'CEDAR OF LEBANON'                   , code:''},
{name:'CHASTE TREE'                        , code:''},
{name:'CHERIMOYA'                          , code:''},
{name:'CHILEAN PEPPER TREE'                , code:''},
{name:'CHILEAN WINE PALM'                  , code:''},
{name:'CHINABERRY'                         , code:''},
{name:'CHINESE COLUMNAR JUNIPER'           , code:''},
{name:'CHINESE ELM'                        , code:''},
{name:'CHINESE EVERGREEN ELM'              , code:''},
{name:'CHINESE FAN PALM'                   , code:''},
{name:'CHINESE FLAME TREE'                 , code:''},
{name:'CHINESE FOUNTAIN PALM'              , code:''},
{name:'CHINESE FRINGE TREE'                , code:''},
{name:'CHINESE HACKBERRY'                  , code:''},
{name:'CHINESE HOLLY'                      , code:''},
{name:'CHINESE JUJUBE'                     , code:''},
{name:'CHINESE JUNIPER'                    , code:''},
{name:'CHINESE LANTERN TREE'               , code:''},
{name:'CHINESE PARASOL TREE'               , code:''},
{name:'CHINESE PHOTINIA'                   , code:''},
{name:'CHINESE PISTACHE'                   , code:''},
{name:'CHINESE SWEETGUM'                   , code:''},
{name:'CHINESE TALLOWTREE'                 , code:''},
{name:'CHINESE WINGNUT'                    , code:''},
{name:'CHINESE WISTERIA'                   , code:''},
{name:'CHIR PINE'                          , code:''},
{name:'CHITALPA'                           , code:''},
{name:'CLIFF DATE PALM'                    , code:''},
{name:'COAST REDWOOD'                      , code:''},
{name:'COCKSPUR CORAL TREE'                , code:''},
{name:'COCONUT PALM'                       , code:''},
{name:'COLORADO BLUE SPRUCE'               , code:''},
{name:'COLORADO JUNIPER'                   , code:''},
{name:'COLORADO RED LOCUST'                , code:''},
{name:'COMMON BANANA'                      , code:''},
{name:'COMMON CATALPA'                     , code:''},
{name:'COMMON GUAVA'                       , code:''},
{name:'COMMON HACKBERRY'                   , code:''},
{name:'COMMON JUNIPER'                     , code:''},
{name:'COMMON LILAC'                       , code:''},
{name:'COMMON MANZANITA'                   , code:''},
{name:'COMMON PERSIMMON'                   , code:''},
{name:'CORAL GUM'                          , code:''},
{name:'CORAL TREE SPECIES'                 , code:''},
{name:'CORK OAK'                           , code:''},
{name:'CORKSCREW WILLOW'                   , code:''},
{name:'COULTER PINE'                       , code:''},
{name:'COYOTE BRUSH'                       , code:''},
{name:'CRABAPPLE'                          , code:''},
{name:'CRAPE MYRTLE'                       , code:''},
{name:'CRIMSON MALLEE BOX'                 , code:''},
{name:'CUNNINGHAM BEEFWOOD'                , code:''},
{name:'CYPRESS'                            , code:''},
{name:'CYPRESS SPECIES'                    , code:''},
{name:'DATE PALM'                          , code:''},
{name:'DAWN REDWOOD'                       , code:''},
{name:'DEAD TREE'                          , code:''},
{name:'DEODAR CEDAR'                       , code:''},
{name:'DESERT GUM'                         , code:''},
{name:'DIGGER PINE'                        , code:''},
{name:'DOGWOOD'                            , code:''},
{name:'DOUGLAS FIR'                        , code:''},
{name:'DRACAENA'                           , code:''},
{name:'DRAGON TREE'                        , code:''},
{name:'DROOPING MELALEUCA'                 , code:''},
{name:'EASTERN REDBUD'                     , code:''},
{name:'EDIBLE APPLE'                       , code:''},
{name:'EDIBLE FIG'                         , code:''},
{name:'EDIBLE LOQUAT'                      , code:''},
{name:'EDIBLE PEAR'                        , code:''},
{name:'ELM SPECIES'                        , code:''},
{name:'ENGELMAN SPRUCE'                    , code:''},
{name:'ENGLISH ELM'                        , code:''},
{name:'ENGLISH HOLLY'                      , code:''},
{name:'ENGLISH WALNUT'                     , code:''},
{name:'ENGLISH YEW'                        , code:''},
{name:'EUCALYPTUS SPECIES'                 , code:''},
{name:'EUROPEAN HACKBERRY'                 , code:''},
{name:'EUROPEAN WHITE BIRCH'               , code:''},
{name:'EVERBLOOMING ACACIA'                , code:''},
{name:'EVERGREEN DOGWOOD'                  , code:''},
{name:'EVERGREEN PEAR'                     , code:''},
{name:'FALSE CYPRESS SPECIES'              , code:''},
{name:'FALSE PINE SPECIES'                 , code:''},
{name:'FAN PALM SPECIES'                   , code:''},
{name:'FERN PINE'                          , code:''},
{name:'FERNLEAF CATALINA IRONWOOD'         , code:''},
{name:'FIDDLELEAF FIG'                     , code:''},
{name:'FIREWHEEL TREE'                     , code:''},
{name:'FISHTAIL PALM'                      , code:''},
{name:'FLAME TREE'                         , code:''},
{name:'FLAMEGOLD'                          , code:''},
{name:'FLANNEL BUSH'                       , code:''},
{name:'FLAX-LEAF PAPERBARK'                , code:''},
{name:'FLOWERING ASH'                      , code:''},
{name:'FLOWERING CHERRY'                   , code:''},
{name:'FLOWERING DOGWOOD'                  , code:''},
{name:'FLOWERING MAPLE'                    , code:''},
{name:'FLOWERING PLUM'                     , code:''},
{name:'FLOWERY SENNA'                      , code:''},
{name:'FOOTHILL ASH'                       , code:''},
{name:'FORBES CYPRESS'                     , code:''},
{name:'FORMOSA SWEETGUM'                   , code:''},
{name:'FRAGRANT OLIVE'                     , code:''},
{name:'FRANGIPANI'                         , code:''},
{name:'FRASER PHOTINIA'                    , code:''},
{name:'FREMONT COTTONWOOD'                 , code:''},
{name:'FULL MOON MAPLE'                    , code:''},
{name:'GIAND BIRD OF PARADISE'             , code:''},
{name:'GIANT ARBORVITAE'                   , code:''},
{name:'GIANT BIRD OF PARADISE SHRUB'       , code:''},
{name:'GIANT YUCCA'                        , code:''},
{name:'GLOBE WILLOW'                       , code:''},
{name:'GLOSSY ARALIA TREE'                 , code:''},
{name:'GLOSSY PRIVET'                      , code:''},
{name:'GOLD MEDALLION TREE'                , code:''},
{name:'GOLDEN TRUMPET TREE'                , code:''},
{name:'GOLDEN WATTLE'                      , code:''},
{name:'GOLDENRAIN TREE'                    , code:''},
{name:'GRAPEFRUIT'                         , code:''},
{name:'GREEN WATTLE'                       , code:''},
{name:'GUADALUPE PALM'                     , code:''},
{name:'GUATEMALAN HOLLY'                   , code:''},
{name:'GUM MYRTLE'                         , code:''},
{name:'GUM-BARKED COOLABAH'                , code:''},
{name:'HACKBERRY SPECIES'                  , code:''},
{name:'HAT TREE'                           , code:''},
{name:'HEATH MELALEUCA'                    , code:''},
{name:'HIBISCUS SPECIES'                   , code:''},
{name:'HIMALAYAN JUNIPER'                  , code:''},
{name:'HIMALAYAN PINE'                     , code:''},
{name:'HOLLY OAK'                          , code:''},
{name:'HOLLY SPECIES'                      , code:''},
{name:'HOLLYLEAF CHERRY'                   , code:''},
{name:'HOLLYWOOD JUNIPER'                  , code:''},
{name:'HOLLYWOOD TWISTED JUNIPER'          , code:''},
{name:'HONEY LOCUST'                       , code:''},
{name:'HONG KONG ORCHID TREE'              , code:''},
{name:'HOOP PINE'                          , code:''},
{name:'HOPSEED'                            , code:''},
{name:'HORSETAIL TREE'                     , code:''},
{name:'HYBRID CATALPA'                     , code:''},
{name:'IDAHO LAVENDER LOCUST'              , code:''},
{name:'INCENSE CEDAR'                      , code:''},
{name:'INDIAN HAWTHORN'                    , code:''},
{name:'INDIAN LAUREL FIG'                  , code:''},
{name:'IRISH YEW'                          , code:''},
{name:'ITALIAN ALDER'                      , code:''},
{name:'ITALIAN BUCKTHORN'                  , code:''},
{name:'ITALIAN CYPRESS'                    , code:''},
{name:'ITALIAN STONE PINE'                 , code:''},
{name:'JACARANDA'                          , code:''},
{name:'JAPANESE BLACK PINE'                , code:''},
{name:'JAPANESE CAMELLIA'                  , code:''},
{name:'JAPANESE CEDAR'                     , code:''},
{name:'JAPANESE FLOWERING APRICOT'         , code:''},
{name:'JAPANESE FLOWERING CHERRY'          , code:''},
{name:'JAPANESE MAPLE'                     , code:''},
{name:'JAPANESE PAGODA TREE'               , code:''},
{name:'JAPANESE PERSIMMON'                 , code:''},
{name:'JAPANESE PLUM'                      , code:''},
{name:'JAPANESE PRIVET'                    , code:''},
{name:'JAPANESE RED PINE'                  , code:''},
{name:'JAPANESE VIBURNUM'                  , code:''},
{name:'JAPANESE YEW PINE'                  , code:''},
{name:'JEFFREY PINE'                       , code:''},
{name:'JELECOTE PINE'                      , code:''},
{name:'JERUSALEM THORN'                    , code:''},
{name:'JUNIPER'                            , code:''},
{name:'JUNIPER SPECIES'                    , code:''},
{name:'KAFFIR PLUM'                        , code:''},
{name:'KAFFIRBOOM CORAL TREE'              , code:''},
{name:'KANGAROO THORN'                     , code:''},
{name:'KARO'                               , code:''},
{name:'KATSURA TREE'                       , code:''},
{name:'KENTIA PALM'                        , code:''},
{name:'KING PALM'                          , code:''},
{name:'KINGANS FRUITLESS MULBERRY'         , code:''},
{name:'KNIFE ACACIA'                       , code:''},
{name:'KNOBCONE PINE'                      , code:''},
{name:'KUMQUAT'                            , code:''},
{name:'LACEBARK PINE'                      , code:''},
{name:'LAUREL SUMAC'                       , code:''},
{name:'LAUREL-LEAF SNAILSEED'              , code:''},
{name:'LAURUSTINUS'                        , code:''},
{name:'LAVENDER CRAPE MYRTLE'              , code:''},
{name:'LAVENDER TRUMPET TREE'              , code:''},
{name:'LAWSON CYPRESS'                     , code:''},
{name:'LEMON'                              , code:''},
{name:'LEMON-SCENTED GUM'                  , code:''},
{name:'LEMONADE BERRY'                     , code:''},
{name:'LEYLAND CYPRESS'                    , code:''},
{name:'LILAC MELALEUCA'                    , code:''},
{name:'LILLY OF THE VALLEY TREE'           , code:''},
{name:'LILLY PILLY TREE'                   , code:''},
{name:'LIME'                               , code:''},
{name:'LIVE OAK'                           , code:''},
{name:'LIVISTONA PALM'                     , code:''},
{name:'LOMBARDY POPLAR'                    , code:''},
{name:'LONDON PLANE'                       , code:''},
{name:'MACADAMIA'                          , code:''},
{name:'MADEIRA BAY FIG'                    , code:''},
{name:'MADRONA'                            , code:''},
{name:'MAIDENHAIR TREE'                    , code:''},
{name:'MANNA GUM'                          , code:''},
{name:'MAPLE SPECIES'                      , code:''},
{name:'MARRI'                              , code:''},
{name:'MAUL OAK'                           , code:''},
{name:'MAUL OAK/CANYON LIVE OAK'           , code:''},
{name:'MAYTEN TREE'                        , code:''},
{name:'MEALY-WHITE GUM'                    , code:''},
{name:'MEDITERRANEAN FAN PALM'             , code:''},
{name:'MELALEUCA'                          , code:''},
{name:'MESA OAK'                           , code:''},
{name:'MEXICAN BLUE PALM'                  , code:''},
{name:'MEXICAN FAN PALM'                   , code:''},
{name:'MEXICAN HAND PLANT'                 , code:''},
{name:'MIMOSA'                             , code:''},
{name:'MOCK ORANGE'                        , code:''},
{name:'MOCKERNUT HICKORY'                  , code:''},
{name:'MODESTO ASH'                        , code:''},
{name:'MONARCH BIRCH'                      , code:''},
{name:'MONKEY PUZZLE TREE'                 , code:''},
{name:'MONTEBELLO ASH'                     , code:''},
{name:'MONTEREY CYPRESS'                   , code:''},
{name:'MONTEREY PINE'                      , code:''},
{name:'MONTEZUMA CYPRESS'                  , code:''},
{name:'MORAINE ASH'                        , code:''},
{name:'MORETON BAY CHESTNUT'               , code:''},
{name:'MORETON-BAY FIG'                    , code:''},
{name:'MOUNTAIN IRONWOOD'                  , code:''},
{name:'MT ATLAS PISTACHE TREE'             , code:''},
{name:'MT. ATLAS MASTIC TREE'              , code:''},
{name:'MYOPORUM'                           , code:''},
{name:'MYRTLE'                             , code:''},
{name:'NAKED CORAL TREE'                   , code:''},
{name:'NATAL CORAL TREE'                   , code:''},
{name:'NATAL PLUM'                         , code:''},
{name:'NECTARINE'                          , code:''},
{name:'NEEDLE PALM'                        , code:''},
{name:'NEW CALEDONIA PINE'                 , code:''},
{name:'NEW ZEALAND CHASTE TREE'            , code:''},
{name:'NEW ZEALAND CHRISTMAS TREE'         , code:''},
{name:'NEW ZEALAND LAUREL'                 , code:''},
{name:'NEW ZEALAND PALM'                   , code:''},
{name:'NONE'                               , code:''},
{name:'NORFOLK ISLAND PINE'                , code:''},
{name:'NORWAY MAPLE'                       , code:''},
{name:'NOSEGAY'                            , code:''},
{name:'OAK SPECIES'                        , code:''},
{name:'OCTOPUS TREE'                       , code:''},
{name:'OLEANDER'                           , code:''},
{name:'OLIVE'                              , code:''},
{name:'ORANGE'                             , code:''},
{name:'OREGON ASH'                         , code:''},
{name:'ORIENTAL ARBORVITAE'                , code:''},
{name:'ORIENTAL SWEETGUM'                  , code:''},
{name:'ORNAMENTAL PEAR'                    , code:''},
{name:'OSAGE ORANGE'                       , code:''},
{name:'OTHER'                              , code:''},
{name:'PACIFIC PLUM'                       , code:''},
{name:'PALM SPECIES'                       , code:''},
{name:'PAPAYA'                             , code:''},
{name:'PAPER BIRCH'                        , code:''},
{name:'PAPER MULBERRY'                     , code:''},
{name:'PARADOX WALNUT'                     , code:''},
{name:'PARANA PINE'                        , code:''},
{name:'PARLOR PALM'                        , code:''},
{name:'PARRY PINYON PINE'                  , code:''},
{name:'PAULS SCARLET HAWTHORN'            , code:''},
{name:'PEACH'                              , code:''},
{name:'PECAN'                              , code:''},
{name:'PENCIL TREE'                        , code:''},
{name:'PEPPERMINT EUCALYPTUS'              , code:''},
{name:'PEPPERMINT TREE'                    , code:''},
{name:'PERUVIAN PEPPER TREE'               , code:''},
{name:'PFITZER JUNIPER'                    , code:''},
{name:'PIN OAK'                            , code:''},
{name:'PINDO PALM'                         , code:''},
{name:'PINE SPECIES'                       , code:''},
{name:'PINEAPPLE GUAVA'                    , code:''},
{name:'PINK BOTTLE TREE'                   , code:''},
{name:'PINK CRAPE MYRTLE'                  , code:''},
{name:'PINK FLOWERING GUM'                 , code:''},
{name:'PINK FLOWERING LOCUST'              , code:''},
{name:'PINK FLOWERING TAMARISK'            , code:''},
{name:'PINK IRONBARK'                      , code:''},
{name:'PINK MELALEUCA'                     , code:''},
{name:'PINK POWDER PUFF'                   , code:''},
{name:'PINK TRUMPET TREE'                  , code:''},
{name:'PINON PINE'                         , code:''},
{name:'PLUM'                               , code:''},
{name:'PLUME ALBIZIA'                      , code:''},
{name:'PLUME CEDAR'                        , code:''},
{name:'POINSETTIA'                         , code:''},
{name:'POMEGRANATE'                        , code:''},
{name:'PONDEROSA PINE'                     , code:''},
{name:'PONYTAIL PALM'                      , code:''},
{name:'POPLAR'                             , code:''},
{name:'PORT ORFORD CEDAR'                  , code:''},
{name:'PORTUGAL LAUREL'                    , code:''},
{name:'POTATO TREE'                        , code:''},
{name:'PRIMROSE TREE'                      , code:''},
{name:'PRINCESS TREE'                      , code:''},
{name:'PURPLE HOPSEED'                     , code:''},
{name:'PURPLE ORCHID TREE'                 , code:''},
{name:'PURPLE-LEAF PLUM'                   , code:''},
{name:'PUSSY WILLOW'                       , code:''},
{name:'PYGMY DATE PALM'                    , code:''},
{name:'QUEEN PALM'                         , code:''},
{name:'QUEENSLAND GREVILLEA'               , code:''},
{name:'QUEENSLAND NUT'                     , code:''},
{name:'QUEENSLAND PITTOSPORUM'             , code:''},
{name:'QUEENSLAND UMBRELLA TREE'           , code:''},
{name:'QUINCE TREE'                        , code:''},
{name:'RAYWOOD ASH'                        , code:''},
{name:'RED ALDER'                          , code:''},
{name:'RED BAY'                            , code:''},
{name:'RED CLUSTERBERRY'                   , code:''},
{name:'RED CRAPE MYRTLE'                   , code:''},
{name:'RED FIR'                            , code:''},
{name:'RED FLOWERING GUM'                  , code:''},
{name:'RED GUM'                            , code:''},
{name:'RED HORSE-CHESTNUT'                 , code:''},
{name:'RED IRONBARK'                       , code:''},
{name:'RED MAHOGANY'                       , code:''},
{name:'RED MAPLE'                          , code:''},
{name:'RED MULBERRY'                       , code:''},
{name:'RED OAK'                            , code:''},
{name:'RED SPRUCE'                         , code:''},
{name:'RED WILLOW'                         , code:''},
{name:'RED-CAP GUM'                        , code:''},
{name:'REDBUD'                             , code:''},
{name:'RIDGE-FRUITED MALLEE'               , code:''},
{name:'RIGIDLEAF MELALEUCA'                , code:''},
{name:'RING-LEAF WILLOW'                   , code:''},
{name:'RIVER BIRCH'                        , code:''},
{name:'RIVER SHE-OAK'                      , code:''},
{name:'ROSE APPLE'                         , code:''},
{name:'ROSE GUM'                           , code:''},
{name:'ROSE-OF-CHINA'                      , code:''},
{name:'ROSE-OF-SHARON'                     , code:''},
{name:'ROUND-LEAF MOORT'                   , code:''},
{name:'ROUNDLEAF SWEETGUM'                 , code:''},
{name:'RUBBER TREE'                        , code:''},
{name:'RUSSIAN OLIVE'                      , code:''},
{name:'RUSTY-LEAF FIG'                     , code:''},
{name:'SAGO PALM'                          , code:''},
{name:'SALTY GUM'                          , code:''},
{name:'SAND PEAR'                          , code:''},
{name:'SANDANKWA VIBURNUM'                 , code:''},
{name:'SANTA CRUZ ISLAND IRONWOOD'         , code:''},
{name:'SAUCER MAGNOLIA'                    , code:''},
{name:'SAWTOOTH ZELKOVA'                   , code:''},
{name:'SCARLET BOTTLEBRUSH'                , code:''},
{name:'SCARLET OAK'                        , code:''},
{name:'SCARLET-PLUME'                      , code:''},
{name:'SCOTCH PINE'                        , code:''},
{name:'SEA-URCHIN TREE'                    , code:''},
{name:'SENEGAL PALM'                       , code:''},
{name:'SHAMEL ASH'                         , code:''},
{name:'SHOESTRING ACACIA'                  , code:''},
{name:'SHORE PINE'                         , code:''},
{name:'SIBERIAN ELM'                       , code:''},
{name:'SILK OAK'                           , code:''},
{name:'SILK TREE'                          , code:''},
{name:'SILK-FLOSS TREE'                    , code:''},
{name:'SILVER DOLLAR GUM'                  , code:''},
{name:'SILVER DOLLAR TREE'                 , code:''},
{name:'SILVER MAPLE'                       , code:''},
{name:'SILVER SAW PALM'                    , code:''},
{name:'SILVER WATTLE'                      , code:''},
{name:'SIRIS TREE'                         , code:''},
{name:'SKY FLOWER'                         , code:''},
{name:'SMALL-LEAVED GUM'                   , code:''},
{name:'SMALLLEAF SWEETGUM'                 , code:''},
{name:'SMOKE TREE'                         , code:''},
{name:'SMOOTH-BARK ARIZONA CYPRESS'        , code:''},
{name:'SO. CALIFORNIA BLACK WALNUT'        , code:''},
{name:'SOAPBARK TREE'                      , code:''},
{name:'SOUR CHERRY'                        , code:''},
{name:'SOUR ORANGE'                        , code:''},
{name:'SOUTHERN LIVE OAK'                  , code:''},
{name:'SOUTHERN MAGNOLIA'                  , code:''},
{name:'SPANISH CHESTNUT'                   , code:''},
{name:'SPANISH DAGGER'                     , code:''},
{name:'SPANISH FIR'                        , code:''},
{name:'SPANISH RED OAK'                    , code:''},
{name:'SPANISH-BAYONET'                    , code:''},
{name:'SPINDLE TREE'                       , code:''},
{name:'SPOTTED GUM'                        , code:''},
{name:'STAR MAGNOLIA'                      , code:''},
{name:'STIFF BOTTLEBRUSH'                  , code:''},
{name:'STONE FRUIT SPECIES'                , code:''},
{name:'STRAWBERRY GUAVA'                   , code:''},
{name:'STRAWBERRY TREE'                    , code:''},
{name:'STRIBLING FRUITLESS MULBERRY'       , code:''},
{name:'STUMP'                              , code:''},
{name:'SUGAR BUSH'                         , code:''},
{name:'SUGAR GUM'                          , code:''},
{name:'SUGAR MAPLE'                        , code:''},
{name:'SWAMP MAHOGONY'                     , code:''},
{name:'SWEET BAY'                          , code:''},
{name:'SWEET BAY MAGNOLIA'                 , code:''},
{name:'SWEET CHERRY'                       , code:''},
{name:'SWEET HAKEA'                        , code:''},
{name:'SWEETSHADE'                         , code:''},
{name:'SWISS MOUNTAIN PINE'                , code:''},
{name:'SYDNEY GOLDEN WATTLE'               , code:''},
{name:'TANBARK OAK'                        , code:''},
{name:'TANGERINE'                          , code:''},
{name:'TARATA'                             , code:''},
{name:'TEA TREE'                           , code:''},
{name:'TECATE CYPRESS'                     , code:''},
{name:'TEXAS PALMETTO'                     , code:''},
{name:'TEXAS UMBRELLA TREE'                , code:''},
{name:'THORNLESS HONEY LOCUST'             , code:''},
{name:'THORNY ELAEAGNUS'                   , code:''},
{name:'TIGER-CLAW CORAL TREE'              , code:''},
{name:'TIPU'                               , code:''},
{name:'TITOKI'                             , code:''},
{name:'TOMLINSON ASH'                      , code:''},
{name:'TORREY PINE'                        , code:''},
{name:'TOYON'                              , code:''},
{name:'TREE ALOE'                          , code:''},
{name:'TREE OF HEAVEN'                     , code:''},
{name:'TREE TOBACCO'                       , code:''},
{name:'TRIDENT MAPLE'                      , code:''},
{name:'TRINIDAD FLAME BUSH'                , code:''},
{name:'TULIP TREE'                         , code:''},
{name:'TUPIDANTHUS'                        , code:''},
{name:'VACANT - OK TO PLANT'               , code:''},
{name:'VACANT PLANTING WELL'               , code:''},
{name:'VACANT/INADEQUATE SPACING'          , code:''},
{name:'VACANT/OK TO REPLANT'               , code:''},
{name:'VACANT/PROP. OWNER OBJECTS'         , code:''},
{name:'VALLEY OAK'                         , code:''},
{name:'VICTORIAN BOX'                      , code:''},
{name:'VIRGINIA LIVE OAK'                  , code:''},
{name:'WALNUT SPECIES'                     , code:''},
{name:'WASHINGTON THORN'                   , code:''},
{name:'WATERMELON RED CRAPE MYRTLE'        , code:''},
{name:'WEEPING BOTTLE BRUSH'               , code:''},
{name:'WEEPING FIG'                        , code:''},
{name:'WEEPING MULBERRY'                   , code:''},
{name:'WEEPING MYALL'                      , code:''},
{name:'WEEPING WILLOW'                     , code:''},
{name:'WESTERN CATALPA'                    , code:''},
{name:'WESTERN HACKBERRY'                  , code:''},
{name:'WESTERN RED CEDAR'                  , code:''},
{name:'WESTERN REDBUD'                     , code:''},
{name:'WHITE ALDER'                        , code:''},
{name:'WHITE BASSWOOD'                     , code:''},
{name:'WHITE BIRCH'                        , code:''},
{name:'WHITE BOTTLE BRUSH'                 , code:''},
{name:'WHITE BOTTLEBRUSH'                  , code:''},
{name:'WHITE CRAPE MYRTLE'                 , code:''},
{name:'WHITE IRONBARK'                     , code:''},
{name:'WHITE MULBERRY'                     , code:''},
{name:'WHITE ORCHID TREE'                  , code:''},
{name:'WHITE PEPPERMINT'                   , code:''},
{name:'WHITE PINE'                         , code:''},
{name:'WHITE POPINAC'                      , code:''},
{name:'WHITE POPLAR'                       , code:''},
{name:'WHITE SAPOTE'                       , code:''},
{name:'WHITE WILLOW'                       , code:''},
{name:'WHITE-FLOWERED MIMOSA'              , code:''},
{name:'WILLOW'                             , code:''},
{name:'WILLOW ACACIA'                      , code:''},
{name:'WILLOW PITTOSPORUM'                 , code:''},
{name:'WILLOW-LEAVED PEPPERMINT'           , code:''},
{name:'WILSON HOLLY'                       , code:''},
{name:'WINDMILL PALM'                      , code:''},
{name:'WOOLLY SENNA'                       , code:''},
{name:'XYLOSMA'                            , code:''},
{name:'YATE'                               , code:''},
{name:'YELLOW OLEANDER'                    , code:''},
{name:'YEW PINE'                           , code:''},
{name:'YOSHINO FLOWERING CHERRY'           , code:''}

];


//=========================================
/*
var allStates = 'Alabama, Alaska, Arizona, Arkansas, California, Colorado, Connecticut, Delaware, Florida, Georgia, Hawaii, Idaho, Illinois, Indiana, Iowa, Kansas, Kentucky, Louisiana, Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana, Nebraska, Nevada, New Hampshire, New Jersey, New Mexico, New York, North Carolina, North Dakota, Ohio, Oklahoma, Oregon, Pennsylvania, Rhode Island, South Carolina, South Dakota, Tennessee, Texas, Utah, Vermont, Virginia, Washington, West Virginia, Wisconsin, Wyoming';

*/

var allStates = 'ABYSSINIAN BANANA, ACACIA SPECIES, AFRICAN FERN PINE, AFRICAN SUMAC, AFRICAN TULIP TREE, ALEPPO PINE, ALLIGATOR JUNIPER, ALMOND, AMERICAN ARBORVITAE, AMERICAN CHESTNUT, AMERICAN ELM, AMERICAN HOLLY, AMERICAN MOUNTAIN ASH, AMERICAN SWEETGUM, AMERICAN SYCAMORE, AMERICAN WHITE ASH, APRICOT, ARAUCARIA SPECIES, ARIZONA ASH, ARIZONA CYPRESS, ARROYO WILLOW, ATHEL TREE, ATLAS CEDAR, AUSTRALIAN BRUSH CHERRY, AUSTRALIAN FAN PALM, AUSTRALIAN JUNIPER-MYRTLE, AUSTRALIAN TEA TREE, AUSTRALIAN TREE FERN, AUSTRALIAN WILLOW, AUSTRIAN PINE, AVOCADO, BAILEY ACACIA, BALD CYPRESS, BALSAM POPLAR, BANYAN FIG, BECHTEL CRABAPPLE, BEECH, BEEFWOOD, BENGAL PALM, BIGLEAF MAPLE, BISHOP PINE, BLACK ACACIA, BLACK ALDER, BLACK COTTONWOOD, BLACK LOCUST, BLACK MULBERRY, BLACK WALNUT, BLACK WILLOW, BLUE ATLAS CEDAR, BLUE BLOSSOM, BLUE ELDERBERRY, BLUE GUM, BLUE POTATO BUSH, BO TREE, BOTTLE TREE, BOTTLEBRUSH, BOWER WATTLE, BOX ELDER, BRADFORD PEAR, BRAZILIAN PEPPER, BRAZILWOOD, BRISBANE BOX, BRONZE LOQUAT, BRUSH CHERRY, BUNYA-BUNYA TREE, BUSHY BLUE GUM, BUSHY YATE, BUSHY YATE/LEHMANS YATE, CAJEPUT TREE, CALABRIAN PINE, CALIFORNIA BAY, CALIFORNIA BIG TREE, CALIFORNIA BLACK OAK, CALIFORNIA BLACK WALNUT, CALIFORNIA BUCKEYE, CALIFORNIA ELDERBERRY, CALIFORNIA FAN PALM, CALIFORNIA JUNIPER, CALIFORNIA NUTMEG, CALIFORNIA PEPPER, CALIFORNIA PRIVET, CALIFORNIA SCRUB OAK, CALIFORNIA SYCAMORE, CAMPHOR TREE, CANARY ISLAND DATE PALM, CANARY ISLAND PINE, CANOE BIRCH, CAPE CHESTNUT, CAPE PITTOSPORUM, CARIBBEE ROYSTONEA PALM, CAROB, CAROLINA LAUREL CHERRY, CAROLINA POPLAR, CARROTWOOD, CATALINA CHERRY, CATALINA IRONWOOD, CEDAR OF LEBANON, CHASTE TREE, CHERIMOYA, CHILEAN PEPPER TREE, CHILEAN WINE PALM, CHINABERRY, CHINESE COLUMNAR JUNIPER, CHINESE ELM, CHINESE EVERGREEN ELM, CHINESE FAN PALM, CHINESE FLAME TREE, CHINESE FOUNTAIN PALM, CHINESE FRINGE TREE, CHINESE HACKBERRY, CHINESE HOLLY, CHINESE JUJUBE, CHINESE JUNIPER, CHINESE LANTERN TREE, CHINESE PARASOL TREE, CHINESE PHOTINIA, CHINESE PISTACHE, CHINESE SWEETGUM, CHINESE TALLOWTREE, CHINESE WINGNUT, CHINESE WISTERIA, CHIR PINE, CHITALPA, CLIFF DATE PALM, COAST REDWOOD, COCKSPUR CORAL TREE, COCONUT PALM, COLORADO BLUE SPRUCE, COLORADO JUNIPER, COLORADO RED LOCUST, COMMON BANANA, COMMON CATALPA, COMMON GUAVA, COMMON HACKBERRY, COMMON JUNIPER, COMMON LILAC, COMMON MANZANITA, COMMON PERSIMMON, CORAL GUM, CORAL TREE SPECIES, CORK OAK, CORKSCREW WILLOW, COULTER PINE, COYOTE BRUSH, CRABAPPLE, CRAPE MYRTLE, CRIMSON MALLEE BOX, CUNNINGHAM BEEFWOOD, CYPRESS, CYPRESS SPECIES, DATE PALM, DAWN REDWOOD, DEAD TREE, DEODAR CEDAR, DESERT GUM, DIGGER PINE, DOGWOOD, DOUGLAS FIR, DRACAENA, DRAGON TREE, DROOPING MELALEUCA, EASTERN REDBUD, EDIBLE APPLE, EDIBLE FIG, EDIBLE LOQUAT, EDIBLE PEAR, ELM SPECIES, ENGELMAN SPRUCE, ENGLISH ELM, ENGLISH HOLLY, ENGLISH WALNUT, ENGLISH YEW, EUCALYPTUS SPECIES, EUROPEAN HACKBERRY, EUROPEAN WHITE BIRCH, EVERBLOOMING ACACIA, EVERGREEN DOGWOOD, EVERGREEN PEAR, FALSE CYPRESS SPECIES, FALSE PINE SPECIES, FAN PALM SPECIES, FERN PINE, FERNLEAF CATALINA IRONWOOD, FIDDLELEAF FIG, FIREWHEEL TREE, FISHTAIL PALM, FLAME TREE, FLAMEGOLD, FLANNEL BUSH, FLAX-LEAF PAPERBARK, FLOWERING ASH, FLOWERING CHERRY, FLOWERING DOGWOOD, FLOWERING MAPLE, FLOWERING PLUM, FLOWERY SENNA, FOOTHILL ASH, FORBES CYPRESS, FORMOSA SWEETGUM, FRAGRANT OLIVE, FRANGIPANI, FRASER PHOTINIA, FREMONT COTTONWOOD, FULL MOON MAPLE, GIAND BIRD OF PARADISE, GIANT ARBORVITAE, GIANT BIRD OF PARADISE SHRUB, GIANT YUCCA, GLOBE WILLOW, GLOSSY ARALIA TREE, GLOSSY PRIVET, GOLD MEDALLION TREE, GOLDEN TRUMPET TREE, GOLDEN WATTLE, GOLDENRAIN TREE, GRAPEFRUIT, GREEN WATTLE, GUADALUPE PALM, GUATEMALAN HOLLY, GUM MYRTLE, GUM-BARKED COOLABAH, HACKBERRY SPECIES, HAT TREE, HEATH MELALEUCA, HIBISCUS SPECIES, HIMALAYAN JUNIPER, HIMALAYAN PINE, HOLLY OAK, HOLLY SPECIES, HOLLYLEAF CHERRY, HOLLYWOOD JUNIPER, HOLLYWOOD TWISTED JUNIPER, HONEY LOCUST, HONG KONG ORCHID TREE, HOOP PINE, HOPSEED, HORSETAIL TREE, HYBRID CATALPA, IDAHO LAVENDER LOCUST, INCENSE CEDAR, INDIAN HAWTHORN, INDIAN LAUREL FIG, IRISH YEW, ITALIAN ALDER, ITALIAN BUCKTHORN, ITALIAN CYPRESS, ITALIAN STONE PINE, JACARANDA, JAPANESE BLACK PINE, JAPANESE CAMELLIA, JAPANESE CEDAR, JAPANESE FLOWERING APRICOT, JAPANESE FLOWERING CHERRY, JAPANESE MAPLE, JAPANESE PAGODA TREE, JAPANESE PERSIMMON, JAPANESE PLUM, JAPANESE PRIVET, JAPANESE RED PINE, JAPANESE VIBURNUM, JAPANESE YEW PINE, JEFFREY PINE, JELECOTE PINE, JERUSALEM THORN, JUNIPER, JUNIPER SPECIES, KAFFIR PLUM, KAFFIRBOOM CORAL TREE, KANGAROO THORN, KARO, KATSURA TREE, KENTIA PALM, KING PALM, KINGANS FRUITLESS MULBERRY, KNIFE ACACIA, KNOBCONE PINE, KUMQUAT, LACEBARK PINE, LAUREL SUMAC, LAUREL-LEAF SNAILSEED, LAURUSTINUS, LAVENDER CRAPE MYRTLE, LAVENDER TRUMPET TREE, LAWSON CYPRESS, LEMON, LEMON-SCENTED GUM, LEMONADE BERRY, LEYLAND CYPRESS, LILAC MELALEUCA, LILLY OF THE VALLEY TREE, LILLY PILLY TREE, LIME, LIVE OAK, LIVISTONA PALM, LOMBARDY POPLAR, LONDON PLANE, MACADAMIA, MADEIRA BAY FIG, MADRONA, MAIDENHAIR TREE, MANNA GUM, MAPLE SPECIES, MARRI, MAUL OAK, MAUL OAK/CANYON LIVE OAK, MAYTEN TREE, MEALY-WHITE GUM, MEDITERRANEAN FAN PALM, MELALEUCA, MESA OAK, MEXICAN BLUE PALM, MEXICAN FAN PALM, MEXICAN HAND PLANT, MIMOSA, MOCK ORANGE, MOCKERNUT HICKORY, MODESTO ASH, MONARCH BIRCH, MONKEY PUZZLE TREE, MONTEBELLO ASH, MONTEREY CYPRESS, MONTEREY PINE, MONTEZUMA CYPRESS, MORAINE ASH, MORETON BAY CHESTNUT, MORETON-BAY FIG, MOUNTAIN IRONWOOD, MT ATLAS PISTACHE TREE, MT. ATLAS MASTIC TREE, MYOPORUM, MYRTLE, NAKED CORAL TREE, NATAL CORAL TREE, NATAL PLUM, NECTARINE, NEEDLE PALM, NEW CALEDONIA PINE, NEW ZEALAND CHASTE TREE, NEW ZEALAND CHRISTMAS TREE, NEW ZEALAND LAUREL, NEW ZEALAND PALM, NONE, NORFOLK ISLAND PINE, NORWAY MAPLE, NOSEGAY, OAK SPECIES, OCTOPUS TREE, OLEANDER, OLIVE, ORANGE, OREGON ASH, ORIENTAL ARBORVITAE, ORIENTAL SWEETGUM, ORNAMENTAL PEAR, OSAGE ORANGE, OTHER, PACIFIC PLUM, PALM SPECIES, PAPAYA, PAPER BIRCH, PAPER MULBERRY, PARADOX WALNUT, PARANA PINE, PARLOR PALM, PARRY PINYON PINE, PAULS SCARLET HAWTHORN, PEACH, PECAN, PENCIL TREE, PEPPERMINT EUCALYPTUS, PEPPERMINT TREE, PERUVIAN PEPPER TREE, PFITZER JUNIPER, PIN OAK, PINDO PALM, PINE SPECIES, PINEAPPLE GUAVA, PINK BOTTLE TREE, PINK CRAPE MYRTLE, PINK FLOWERING GUM, PINK FLOWERING LOCUST, PINK FLOWERING TAMARISK, PINK IRONBARK, PINK MELALEUCA, PINK POWDER PUFF, PINK TRUMPET TREE, PINON PINE, PLUM, PLUME ALBIZIA, PLUME CEDAR, POINSETTIA, POMEGRANATE, PONDEROSA PINE, PONYTAIL PALM, POPLAR, PORT ORFORD CEDAR, PORTUGAL LAUREL, POTATO TREE, PRIMROSE TREE, PRINCESS TREE, PURPLE HOPSEED, PURPLE ORCHID TREE, PURPLE-LEAF PLUM, PUSSY WILLOW, PYGMY DATE PALM, QUEEN PALM, QUEENSLAND GREVILLEA, QUEENSLAND NUT, QUEENSLAND PITTOSPORUM, QUEENSLAND UMBRELLA TREE, QUINCE TREE, RAYWOOD ASH, RED ALDER, RED BAY, RED CLUSTERBERRY, RED CRAPE MYRTLE, RED FIR, RED FLOWERING GUM, RED GUM, RED HORSE-CHESTNUT, RED IRONBARK, RED MAHOGANY, RED MAPLE, RED MULBERRY, RED OAK, RED SPRUCE, RED WILLOW, RED-CAP GUM, REDBUD, RIDGE-FRUITED MALLEE, RIGIDLEAF MELALEUCA, RING-LEAF WILLOW, RIVER BIRCH, RIVER SHE-OAK, ROSE APPLE, ROSE GUM, ROSE-OF-CHINA, ROSE-OF-SHARON, ROUND-LEAF MOORT, ROUNDLEAF SWEETGUM, RUBBER TREE, RUSSIAN OLIVE, RUSTY-LEAF FIG, SAGO PALM, SALTY GUM, SAND PEAR, SANDANKWA VIBURNUM, SANTA CRUZ ISLAND IRONWOOD, SAUCER MAGNOLIA, SAWTOOTH ZELKOVA, SCARLET BOTTLEBRUSH, SCARLET OAK, SCARLET-PLUME, SCOTCH PINE, SEA-URCHIN TREE, SENEGAL PALM, SHAMEL ASH, SHOESTRING ACACIA, SHORE PINE, SIBERIAN ELM, SILK OAK, SILK TREE, SILK-FLOSS TREE, SILVER DOLLAR GUM, SILVER DOLLAR TREE, SILVER MAPLE, SILVER SAW PALM, SILVER WATTLE, SIRIS TREE, SKY FLOWER, SMALL-LEAVED GUM, SMALLLEAF SWEETGUM, SMOKE TREE, SMOOTH-BARK ARIZONA CYPRESS, SO. CALIFORNIA BLACK WALNUT, SOAPBARK TREE, SOUR CHERRY, SOUR ORANGE, SOUTHERN LIVE OAK, SOUTHERN MAGNOLIA, SPANISH CHESTNUT, SPANISH DAGGER, SPANISH FIR, SPANISH RED OAK, SPANISH-BAYONET, SPINDLE TREE, SPOTTED GUM, STAR MAGNOLIA, STIFF BOTTLEBRUSH, STONE FRUIT SPECIES, STRAWBERRY GUAVA, STRAWBERRY TREE, STRIBLING FRUITLESS MULBERRY, STUMP, SUGAR BUSH, SUGAR GUM, SUGAR MAPLE, SWAMP MAHOGONY, SWEET BAY, SWEET BAY MAGNOLIA, SWEET CHERRY, SWEET HAKEA, SWEETSHADE, SWISS MOUNTAIN PINE, SYDNEY GOLDEN WATTLE, TANBARK OAK, TANGERINE, TARATA, TEA TREE, TECATE CYPRESS, TEXAS PALMETTO, TEXAS UMBRELLA TREE, THORNLESS HONEY LOCUST, THORNY ELAEAGNUS, TIGER-CLAW CORAL TREE, TIPU, TITOKI, TOMLINSON ASH, TORREY PINE, TOYON, TREE ALOE, TREE OF HEAVEN, TREE TOBACCO, TRIDENT MAPLE, TRINIDAD FLAME BUSH, TULIP TREE, TUPIDANTHUS, VACANT - OK TO PLANT, VACANT PLANTING WELL, VACANT/INADEQUATE SPACING, VACANT/OK TO REPLANT, VACANT/PROP. OWNER OBJECTS, VALLEY OAK, VICTORIAN BOX, VIRGINIA LIVE OAK, WALNUT SPECIES, WASHINGTON THORN, WATERMELON RED CRAPE MYRTLE, WEEPING BOTTLE BRUSH, WEEPING FIG, WEEPING MULBERRY, WEEPING MYALL, WEEPING WILLOW, WESTERN CATALPA, WESTERN HACKBERRY, WESTERN RED CEDAR, WESTERN REDBUD, WHITE ALDER, WHITE BASSWOOD, WHITE BIRCH, WHITE BOTTLE BRUSH, WHITE BOTTLEBRUSH, WHITE CRAPE MYRTLE, WHITE IRONBARK, WHITE MULBERRY, WHITE ORCHID TREE, WHITE PEPPERMINT, WHITE PINE, WHITE POPINAC, WHITE POPLAR, WHITE SAPOTE, WHITE WILLOW, WHITE-FLOWERED MIMOSA, WILLOW, WILLOW ACACIA, WILLOW PITTOSPORUM, WILLOW-LEAVED PEPPERMINT, WILSON HOLLY, WINDMILL PALM, WOOLLY SENNA, XYLOSMA, YATE, YELLOW OLEANDER, YEW PINE, YOSHINO FLOWERING CHERRY';


//===============================================
/*
function getStates() {
    return [{
        "name": "Alabama",
        "abbreviation": "AL"
    }, {
        "name": "Alaska",
        "abbreviation": "AK"
    }, {
        "name": "American Samoa",
        "abbreviation": "AS"
    }, {
        "name": "Arizona",
        "abbreviation": "AZ"
    }, {
        "name": "Arkansas",
        "abbreviation": "AR"
    }, {
        "name": "California",
        "abbreviation": "CA"
    }, {
        "name": "Colorado",
        "abbreviation": "CO"
    }, {
        "name": "Connecticut",
        "abbreviation": "CT"
    }, {
        "name": "Delaware",
        "abbreviation": "DE"
    }, {
        "name": "District Of Columbia",
        "abbreviation": "DC"
    }, {
        "name": "Federated States Of Micronesia",
        "abbreviation": "FM"
    }, {
        "name": "Florida",
        "abbreviation": "FL"
    }, {
        "name": "Georgia",
        "abbreviation": "GA"
    }, {
        "name": "Guam",
        "abbreviation": "GU"
    }, {
        "name": "Hawaii",
        "abbreviation": "HI"
    }, {
        "name": "Idaho",
        "abbreviation": "ID"
    }, {
        "name": "Illinois",
        "abbreviation": "IL"
    }, {
        "name": "Indiana",
        "abbreviation": "IN"
    }, {
        "name": "Iowa",
        "abbreviation": "IA"
    }, {
        "name": "Kansas",
        "abbreviation": "KS"
    }, {
        "name": "Kentucky",
        "abbreviation": "KY"
    }, {
        "name": "Louisiana",
        "abbreviation": "LA"
    }, {
        "name": "Maine",
        "abbreviation": "ME"
    }, {
        "name": "Marshall Islands",
        "abbreviation": "MH"
    }, {
        "name": "Maryland",
        "abbreviation": "MD"
    }, {
        "name": "Massachusetts",
        "abbreviation": "MA"
    }, {
        "name": "Michigan",
        "abbreviation": "MI"
    }, {
        "name": "Minnesota",
        "abbreviation": "MN"
    }, {
        "name": "Mississippi",
        "abbreviation": "MS"
    }, {
        "name": "Missouri",
        "abbreviation": "MO"
    }, {
        "name": "Montana",
        "abbreviation": "MT"
    }, {
        "name": "Nebraska",
        "abbreviation": "NE"
    }, {
        "name": "Nevada",
        "abbreviation": "NV"
    }, {
        "name": "New Hampshire",
        "abbreviation": "NH"
    }, {
        "name": "New Jersey",
        "abbreviation": "NJ"
    }, {
        "name": "New Mexico",
        "abbreviation": "NM"
    }, {
        "name": "New York",
        "abbreviation": "NY"
    }, {
        "name": "North Carolina",
        "abbreviation": "NC"
    }, {
        "name": "North Dakota",
        "abbreviation": "ND"
    }, {
        "name": "Northern Mariana Islands",
        "abbreviation": "MP"
    }, {
        "name": "Ohio",
        "abbreviation": "OH"
    }, {
        "name": "Oklahoma",
        "abbreviation": "OK"
    }, {
        "name": "Oregon",
        "abbreviation": "OR"
    }, {
        "name": "Palau",
        "abbreviation": "PW"
    }, {
        "name": "Pennsylvania",
        "abbreviation": "PA"
    }, {
        "name": "Puerto Rico",
        "abbreviation": "PR"
    }, {
        "name": "Rhode Island",
        "abbreviation": "RI"
    }, {
        "name": "South Carolina",
        "abbreviation": "SC"
    }, {
        "name": "South Dakota",
        "abbreviation": "SD"
    }, {
        "name": "Tennessee",
        "abbreviation": "TN"
    }, {
        "name": "Texas",
        "abbreviation": "TX"
    }, {
        "name": "Utah",
        "abbreviation": "UT"
    }, {
        "name": "Vermont",
        "abbreviation": "VT"
    }, {
        "name": "Virgin Islands",
        "abbreviation": "VI"
    }, {
        "name": "Virginia",
        "abbreviation": "VA"
    }, {
        "name": "Washington",
        "abbreviation": "WA"
    }, {
        "name": "West Virginia",
        "abbreviation": "WV"
    }, {
        "name": "Wisconsin",
        "abbreviation": "WI"
    }, {
        "name": "Wyoming",
        "abbreviation": "WY"
    }];
}
	*/												