<!DOCTYPE html>
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<title>(SRR) Sidewalk Repair Rebate Program - City of Los Angeles</title>
<style>
.highlight {
background: #FFFF00;
}

* {
font-family: arial, verdana;
font-size:100%;
}

a, a:visited {
color:blue;
}
</style>

<body>
<div style="width:750px;margin-left:auto;margin-right:auto;margin-top:5px;border:1px solid gray;border-radius:7px;padding:15px;">
This email is auto-generated by MyLA311 once a reason/resolution code is updated.
</div>
<div style="width:750px;margin-left:auto;margin-right:auto;margin-top:10px;border:1px solid gray;border-radius:7px;padding:15px;">
<img src="../images/email_template_top_noBOE.png" alt="" width="238" height="120" border="0">

<p>Your [Service Request] request was updated on <span class="highlight">[MM/DD/YYYY HH:MM AM/PM]</span>.</p>

<p>
<strong>Service Request Number<span class="highlight">1-121352081</span></strong>
<br>
<strong>Location: <span class="highlight">1149 S BROADWAY, 90015</strong></span>
<br>
<strong>Status: <span class="highlight"><span class="highlight">[Pending]</span></strong></span><br>
<strong>Status: <span class="highlight"><span class="highlight">[You have 90 days to complete construction]</span></strong></span>
</p>

<p>
Recent comments:<br>
<span class="highlight">Thank you for your participation in the City of Los Angeles Sidewalk Rebate Program. Our records indicate that you have obtained a Class A-Permit and a Tree Removal/Root Pruning Permit. You now have 90 calendar days from the date of issuance of your Class A-Permit to properly complete the sidewalk repairs which gives a deadline of [insert Issued date +90 calendar days].
<br><br>Please be sure to call for inspection prior to performing the repairs as outlined on your Class A-Permit in order to ensure that the repair is properly recorded.
</span>
</p>

<br>
<p>
You can check the status of your request by<br>
1.	Visiting <a href="http://myla311.lacity.org" target="_blank">http://myla311.lacity.org</a> <br>
2.	Using the mobile app from <a href="https://play.google.com/store/apps/details?id=com.LA.MyLA311&hl=en" target="_blank">Google Play</a> or the <a href="https://itunes.apple.com/us/app/myla311/id611079486" target="_blank">Apple Store</a><br>
3.	Contacting MyLA311 with your Service Request number (see below for numbers)<br>
<br><br>
Within City of Los Angeles, dial 311<br>
Outside the greater Los Angeles area, dial (213) 473-3231<br>
For the hearing impaired, dial TDD Number (213) 473-5990<br>
The 311 Call Center operating hours are 8:00 am - 4:45 pm daily including weekends and all holidays except Thanksgiving Day and Christmas Day.
</p>


<p>For more information on the Sidewalk Program, go to: <a href="http://sidewalks.lacity.org" target="_blank">sidewalks.lacity.org</a></p>
</div>
